services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockmanager_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - stockmanager_network

  nginx:
    image: nginx:latest
    container_name: stockmanager_nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - stockmanager_network

  db:
    image: mysql:8.0
    container_name: stockmanager_db
    restart: always
    environment:
      MYSQL_DATABASE: stockmanager
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yahya
      MYSQL_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - stockmanager_network

networks:
  stockmanager_network:

volumes:
  dbdata: